name: Build with Yarn
on: push

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Enable corepack
              run: corepack enable

            - name: Install Yarn 4
              run: corepack prepare yarn@4 --activate

            - uses: actions/setup-node@v4
              with:
                  node-version: '20.9.0'
                  cache: 'yarn'

            - name: Position to directory
              run: cd yarn

            - name: Install dependencies
              run: yarn install

            - name: Build app
              run: yarn run build

            - name: Disable corepack
              run: corepack disable